### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Learning Lab
email: contact@sandoche.com
description: Learn one topic every month
baseurl: "/" # the subpath of your site, e.g. /blog
url: "UA-109152683-2" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#CF3D5E'
twitter_username: sandochee
github_username:  sandoche
author: Sandoche Adittane
logo: assets/images/large-logo.png
twitter:
  username: sandochee
social:
  name: Sandoche Adittane
  links:
    - https://twitter.com/sandochee
    - https://github.com/sandoche
    - https://medium.com/learning-lab

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell: appKey
#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png

include:
  - _headers
